### ISSUE TITLE
Move non-compile targets to luigi

### ISSUE THREAD

**Issue by ezubaric** [Pinafore/qb#30]
Since wikification depends on the questions, this should not be in the makefile.  If the questions change, this needs to be rerun.

# Tasks

- [x] Move glove target to luigi
- [x] Move wikipedia target to luigi
- [x] Move kenlm target to luigi
- [x] Move wikifier targets to luigi
- [x] Rename/move wikifier targets from `data/external` to `output`
- [x] Rename/move wikipedia target from `data/external` to `output`

**Comment by EntilZha** [comment]
Agreed, there are a couple other places like this when I looked after we chatted.

**Comment by EntilZha** [comment]
They should also have their destinations changed to `output` to conform to behavior that `rm -rf output` should trigger a full pipeline rerun aside from things that are external to our system (eg glove or compile steps like clm)

**Comment by EntilZha** [comment]
Going to do half the work for this and move this to luigi. Will leave renaming things correctly for later.

**Comment by EntilZha** [comment]
Work is done for this ticket, verifying that the pipeline runs until DAN completion before closing
